version: '3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "6306:3306"
    command:
      - --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=!QAZ2wsx3edc
      #- MYSQL_DATABASE=jiradb
      #- MYSQL_USER=jiradb
      #- MYSQL_PASSWORD=jellyfish
    volumes:
      - ~/data/mysql:/var/lib/mysql
      - ~/data/mysqlconf/:/etc/mysql/
