version: '3'
services:
  database:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=jiradb
      - MYSQL_USER=jiradb
      - MYSQL_PASSWORD=jellyfish
    volumes:
      - ~/data/mysql:/var/lib/mysql
